### PR TITLE
Merge pull request #16 from hungnh103/advanced-login

### PR DESCRIPTION
**Pull request by hungnh103**
Advanced login

### CODE REVIEW

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
reviewing

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
reviewing

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
reviewing

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
reviewing

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
ready

**Comment by hungnh103** [comment]
commented

**Comment by hungnh103** [comment]
ready

**Comment by nvtanh** [comment]
merged

**Comment by nvtanh** [comment]
ready

**Comment by nvtanh** [comment]
merged

**Comment by hungnh103** [comment]
commented

**Pull request merged**
